rrb:
  channels:
    logging: logging:log
    contestStarted: "events:contest-started"
    contestStopped: "events:contest-started"
    contestCreated: "events:contest-created"
    contestDeleted: "events:contest-deleted"
  queues:
    contestsCreate: "contests:create"
    contestsStart: "contests:start"
    contestsStop: "contests:stop"
    contestsDelete: "contests:delete"
    contestsList: "contests:list"
    contestsTop: "contests:top"

redis: # The redis config to use
  prefix: "mh:test:"
  port: 6379
  host: 127.0.0.1

mongodb:
  connectionString: <>
  database: test
  collectionContests: contests
  collectionMemes: memes
    